name: packet_pals
description: A cross-platform app to promote STEM learning through network discovery.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.3.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  json_annotation: ^4.8.0
  # share_plus: ^6.3.0  # Removed
  # Add flutter_share if you choose to use it as an alternative
  flutter_share: ^2.0.0
  # ... other dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock_data.json
